FROM golang:1.20.3-alpine3.17

COPY . /go/src/github.com/GoogleCloudPlatform/kubernetes
WORKDIR /go/src/github.com/GoogleCloudPlatform/kubernetes

RUN go build -o /usr/local/bin/kube-scheduler ./cmd/kube-scheduler

CMD ["/usr/local/bin/kube-scheduler"]
